---
- include_tasks: nomad_parse.yml

- block:
    - name: Create job plan
      uri:
        url: "{{ nomad_job_api }}/job/{{ job_id }}/plan"
        validate_certs: no
        headers:
          X-Nomad-Token: "{{ lookup('env', 'NOMAD_TOKEN') | default(nomad_token, True) }}"
        method: POST
        body: "{{ body_content | to_json }}"
        body_format: json
      vars:
        body_content:
          Job: "{{ job_json.json }}"
          Diff: true
      register: __status

    - name: Show diff
      debug:
        msg: "{{ __status.json.Diff }}"

    - name: Show summary
      debug:
        msg: "{{ __status.json.Annotations.DesiredTGUpdates }}"
  check_mode: no

- block:
    - name: Create/Update existing job
      uri:
        url: "{{ nomad_job_api }}/job/{{ job_id }}"
        validate_certs: no
        headers:
          X-Nomad-Token: "{{ lookup('env', 'NOMAD_TOKEN') | default(nomad_token, True) }}"
        method: POST
        body: "{{ body_content | to_json }}"
        body_format: json
      vars:
        body_content:
          Job: "{{ job_json.json }}"
      register: __status

    - name: Show result
      debug:
        msg: "{{ __status.json }}"
  when: not ansible_check_mode
